export enum Interval {
  //Midi Based Intervals
  UNISON = 0,
  HALF_STEP = 1,
  MINOR_SECOND = 1,
  MAJOR_SECOND = 2,
  WHOLE_STEP = 2,
  MINOR_THIRD = 3,
  MAJOR_THIRD = 4,
  PERFECT_FOURTH = 5,
  TRITONE = 6,
  DIMINISHED_FIFTH = 6,
  PERFECT_FIFTH = 7,
  MINOR_SIXTH = 8,
  AUGMENTED_FIFTH = 8,
  MAJOR_SIXTH = 9,
  MINOR_SEVENTH = 10,
  MAJOR_SEVENTH = 11,
  OCTAVE = 12,
}

export const textForInterval = {
  [Interval.UNISON]: "Unison",
  [Interval.HALF_STEP]: "Half Step",
  [Interval.WHOLE_STEP]: "Whole Step",
  [Interval.MINOR_THIRD]: "Minor Third",
  [Interval.MAJOR_THIRD]: "Major Third",
  [Interval.PERFECT_FOURTH]: "Perfect Fourth",
  [Interval.TRITONE]: "Tritone",
  [Interval.PERFECT_FIFTH]: "Perfect Fifth",
  [Interval.MINOR_SIXTH]: "Minor Sixth",
  [Interval.MAJOR_SIXTH]: "Major Sixth",
  [Interval.MINOR_SEVENTH]: "Minor Seventh",
  [Interval.MAJOR_SEVENTH]: "Major Seventh",
  [Interval.OCTAVE]: "Octave",
};
