import { Interval } from "./intervals";

export enum Scale {
  major = "major (ionian)",
  minor = "minor (aeolian)",
  harmonicMinor = "harmonic minor",
  melodicMinor = "melodic minor",
  dorian = "dorian",
  phrygian = "phrygian",
  lydian = "lydian",
  mixolydian = "mixolydian",
  locrian = "locrian",
  chromatic = "chromatic",
}

export const scaleToInterval = {
  [Scale.chromatic]: [
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
    Interval.HALF_STEP,
  ],
  [Scale.major]: [
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
  ],
  [Scale.minor]: [
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
  ],
  [Scale.harmonicMinor]: [
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP + Interval.HALF_STEP,
    Interval.HALF_STEP,
  ],
  [Scale.melodicMinor]: [
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
  ],
  [Scale.dorian]: [
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
  ],
  [Scale.phrygian]: [
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
  ],
  [Scale.lydian]: [
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
  ],
  [Scale.mixolydian]: [
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
  ],
  [Scale.locrian]: [
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.HALF_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
    Interval.WHOLE_STEP,
  ],
};
