import { HALF_STEP, WHOLE_STEP } from "./intervals";

export enum Scale {
  major = "major (ionian)",
  minor = "minor (aeolian)",
  harmonicMinor = "harmonic minor",
  melodicMinor = "melodic minor",
  dorian = "dorian",
  phrygian = "phrygian",
  lydian = "lydian",
  mixolydian = "mixolydian",
  locrian = "locrian",
  chromatic = "chromatic",
}

export const scaleToInterval = {
  [Scale.chromatic]: [
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
    HALF_STEP,
  ],
  [Scale.major]: [
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
  ],
  [Scale.minor]: [
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
  ],
  [Scale.harmonicMinor]: [
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP + HALF_STEP,
    HALF_STEP,
  ],
  [Scale.melodicMinor]: [
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
  ],
  [Scale.dorian]: [
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
  ],
  [Scale.phrygian]: [
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
  ],
  [Scale.lydian]: [
    WHOLE_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
  ],
  [Scale.mixolydian]: [
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
  ],
  [Scale.locrian]: [
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    HALF_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
    WHOLE_STEP,
  ],
};
